In [1]:
# Import package
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scanpy as sc
import igraph
import scvelo as scv
import loompy as lmp
import anndata as ad
import harmonypy as hm
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

import celltypist
from celltypist import models
from celltypist.models import Model

/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/jaehyunchoi/.conda/envs/test02/lib/python3.10/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)

In [2]:
adata_122960=sc.read("/home/jaehyunchoi/bystander_collaboration/IPF_data/GSE122960/analysis/GSE122960_adata_001.h5ad")
adata_122960

AnnData object with n_obs × n_vars = 74216 × 33694
    obs: 'sample', 'state', 'n_counts', 'n_genes', 'mt_frac'

In [3]:
adata_122960.obs['nCount_RNA'] = adata_122960.obs['n_counts']
adata_122960.obs['nFeature_RNA'] = adata_122960.obs['n_genes']
adata_122960.obs['percent.mt'] = adata_122960.obs['mt_frac']
adata_122960.obs

,sample,state,n_counts,n_genes,mt_frac,nCount_RNA,nFeature_RNA,percent.mt
AAACCTGAGCGTTTAC-1-adata_GSM3489182,adata_GSM3489182,Donor,7743.0,2034,0.046494,7743.0,2034,0.046494
AAACCTGAGTCGCCGT-1-adata_GSM3489182,adata_GSM3489182,Donor,22427.0,4158,0.056271,22427.0,4158,0.056271
AAACCTGGTAGGACAC-1-adata_GSM3489182,adata_GSM3489182,Donor,8346.0,2204,0.059190,8346.0,2204,0.059190
AAACCTGGTGCCTTGG-1-adata_GSM3489182,adata_GSM3489182,Donor,8669.0,2298,0.070135,8669.0,2298,0.070135
AAACCTGGTTCAGCGC-1-adata_GSM3489182,adata_GSM3489182,Donor,3477.0,1300,0.077941,3477.0,1300,0.077941
...,...,...,...,...,...,...,...,...
TTTGTCATCATACGGT-1-adata_GSM3489198,adata_GSM3489198,SSc-ILD,9732.0,2531,0.041307,9732.0,2531,0.041307
TTTGTCATCATGTCTT-1-adata_GSM3489198,adata_GSM3489198,SSc-ILD,5342.0,1401,0.034631,5342.0,1401,0.034631
TTTGTCATCGAACTGT-1-adata_GSM3489198,adata_GSM3489198,SSc-ILD,24478.0,4108,0.058461,24478.0,4108,0.058461
TTTGTCATCGCCCTTA-1-adata_GSM3489198,adata_GSM3489198,SSc-ILD,5072.0,1648,0.046727,5072.0,1648,0.046727
TTTGTCATCGCGTAGC-1-adata_GSM3489198,adata_GSM3489198,SSc-ILD,10887.0,2398,0.038486,10887.0,2398,0.038486

In [4]:
adata_122960.obs = adata_122960.obs[['nCount_RNA', 'nFeature_RNA','sample', 'state']].copy()
adata_122960.obs['state'] = adata_122960.obs['state'].replace('donor', 'Control')
adata_122960.obs

,nCount_RNA,nFeature_RNA,sample,state
AAACCTGAGCGTTTAC-1-adata_GSM3489182,7743.0,2034,adata_GSM3489182,Donor
AAACCTGAGTCGCCGT-1-adata_GSM3489182,22427.0,4158,adata_GSM3489182,Donor
AAACCTGGTAGGACAC-1-adata_GSM3489182,8346.0,2204,adata_GSM3489182,Donor
AAACCTGGTGCCTTGG-1-adata_GSM3489182,8669.0,2298,adata_GSM3489182,Donor
AAACCTGGTTCAGCGC-1-adata_GSM3489182,3477.0,1300,adata_GSM3489182,Donor
...,...,...,...,...
TTTGTCATCATACGGT-1-adata_GSM3489198,9732.0,2531,adata_GSM3489198,SSc-ILD
TTTGTCATCATGTCTT-1-adata_GSM3489198,5342.0,1401,adata_GSM3489198,SSc-ILD
TTTGTCATCGAACTGT-1-adata_GSM3489198,24478.0,4108,adata_GSM3489198,SSc-ILD
TTTGTCATCGCCCTTA-1-adata_GSM3489198,5072.0,1648,adata_GSM3489198,SSc-ILD
TTTGTCATCGCGTAGC-1-adata_GSM3489198,10887.0,2398,adata_GSM3489198,SSc-ILD

In [5]:
adata_135893=sc.read("/home/jaehyunchoi/bystander_collaboration/IPF_data/GSE135893/GSE135893_adata_001.h5ad")
adata_135893

AnnData object with n_obs × n_vars = 114396 × 33694
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'Diagnosis', 'Sample_Name', 'Sample_Source', 'Status', 'percent.mt', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters', 'population', 'celltype'
    var: 'gene_name'

In [6]:
adata_135893.obs['state'] = adata_135893.obs['Diagnosis']
adata_135893.obs['sample'] = adata_135893.obs['orig.ident']
adata_135893.obs

,orig.ident,nCount_RNA,nFeature_RNA,Diagnosis,Sample_Name,Sample_Source,Status,percent.mt,nCount_SCT,nFeature_SCT,seurat_clusters,population,celltype,state,sample
F01157_AAACCTGAGCATCATC,F01157,18200,4259,Control,THD0001,DNA,Control,4.697802,7719,3107,9,Epithelial,AT2,Control,F01157
F01157_AAACCTGTCATGCTCC,F01157,13747,3492,Control,THD0001,DNA,Control,4.044519,7689,3102,9,Epithelial,AT2,Control,F01157
F01157_AAACGGGGTTACGACT,F01157,17756,3604,Control,THD0001,DNA,Control,2.799054,7570,2570,9,Epithelial,AT2,Control,F01157
F01157_AAACGGGGTTAGTGGG,F01157,15767,3856,Control,THD0001,DNA,Control,3.266316,7759,3159,9,Epithelial,AT2,Control,F01157
F01157_AAACGGGTCCTTTCGG,F01157,15483,4104,Control,THD0001,DNA,Control,8.538397,7874,3470,30,Epithelial,Proliferating Epithelial Cells,Control,F01157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F01392_TTTGGTTTCTCTTGAT,F01392,8003,2664,IPF,VUILD65,Vanderbilt,Disease,6.172685,7105,2664,0,Epithelial,SCGB3A2+,IPF,F01392
F01392_TTTGTCACACCCAGTG,F01392,14250,3713,IPF,VUILD65,Vanderbilt,Disease,7.452632,7882,3314,20,Epithelial,MUC5AC+ High,IPF,F01392
F01392_TTTGTCACAGATGGGT,F01392,3360,1825,IPF,VUILD65,Vanderbilt,Disease,9.940476,5353,1869,2,Epithelial,Ciliated,IPF,F01392
F01392_TTTGTCATCTCATTCA,F01392,3446,1355,IPF,VUILD65,Vanderbilt,Disease,7.022635,5815,1364,3,Immune,Macrophages,IPF,F01392
F01392_TTTGTCATCTTGTACT,F01392,4345,1585,IPF,VUILD65,Vanderbilt,Disease,6.306099,5794,1585,12,Epithelial,SCGB3A2+ SCGB1A1+,IPF,F01392

In [7]:
adata_135893.obs = adata_135893.obs[['nCount_RNA', 'nFeature_RNA','sample', 'state']].copy()
adata_135893.obs

                         nCount_RNA  nFeature_RNA  sample    state
F01157_AAACCTGAGCATCATC       18200          4259  F01157  Control
F01157_AAACCTGTCATGCTCC       13747          3492  F01157  Control
F01157_AAACGGGGTTACGACT       17756          3604  F01157  Control
F01157_AAACGGGGTTAGTGGG       15767          3856  F01157  Control
F01157_AAACGGGTCCTTTCGG       15483          4104  F01157  Control
...                             ...           ...     ...      ...
F01392_TTTGGTTTCTCTTGAT        8003          2664  F01392      IPF
F01392_TTTGTCACACCCAGTG       14250          3713  F01392      IPF
F01392_TTTGTCACAGATGGGT        3360          1825  F01392      IPF
F01392_TTTGTCATCTCATTCA        3446          1355  F01392      IPF
F01392_TTTGTCATCTTGTACT        4345          1585  F01392      IPF

[114396 rows x 4 columns]

In [8]:
adata_136831=sc.read("/home/jaehyunchoi/bystander_collaboration/IPF_data/GSE136831/GSE136831_adata_001.h5ad")
adata_136831

AnnData object with n_obs × n_vars = 312928 × 45947
    obs: 'nUMI', 'nGene', 'CellType_Category', 'Manuscript_Identity', 'Subclass_Cell_Identity', 'Disease_Identity', 'Subject_Identity', 'Library_Identity'

In [9]:
adata_136831.obs['state'] = adata_136831.obs['Disease_Identity']
adata_136831.obs['sample'] = adata_136831.obs['Subject_Identity']
adata_136831.obs['nCount_RNA'] = adata_136831.obs['nUMI']
adata_136831.obs['nFeature_RNA'] = adata_136831.obs['nGene']
adata_136831.obs

,nUMI,nGene,CellType_Category,Manuscript_Identity,Subclass_Cell_Identity,Disease_Identity,Subject_Identity,Library_Identity,state,sample,nCount_RNA,nFeature_RNA
001C_AAACCTGCATCGGGTC,5477,2150,Myeloid,ncMonocyte,Monocyte_Non-Classical,Control,001C,001C,Control,001C,5477,2150
001C_AAACCTGTCAACACCA,20311,4726,Myeloid,Macrophage_Alveolar,Macrophage_Alveolar,Control,001C,001C,Control,001C,20311,4726
001C_AAACCTGTCACAGTAC,1390,881,Lymphoid,NK,NK,Control,001C,001C,Control,001C,1390,881
001C_AAACCTGTCTGTCTAT,3968,1943,Myeloid,cMonocyte,Monocyte,Control,001C,001C,Control,001C,3968,1943
001C_AAACGGGAGACTAAGT,3036,1716,Endothelial,Lymphatic,Lymphatic-Endothelial,Control,001C,001C,Control,001C,3036,1716
...,...,...,...,...,...,...,...,...,...,...,...,...
8CO_TTGTAGGCATCACGTA,7617,2796,Lymphoid,T_Cytotoxic,T_Cytotoxic_A,COPD,8CO,8CO,COPD,8CO,7617,2796
8CO_TTGTAGGTCCAGATCA,3904,1811,Myeloid,cMonocyte,Monocyte,COPD,8CO,8CO,COPD,8CO,3904,1811
8CO_TTTATGCGTAGGCTGA,5195,2098,Endothelial,VE_Venous,Vascular-Endothelial_A,COPD,8CO,8CO,COPD,8CO,5195,2098
8CO_TTTGGTTTCTGCAAGT,24743,4819,Myeloid,Macrophage_Alveolar,Macrophage_Alveolar,COPD,8CO,8CO,COPD,8CO,24743,4819
8CO_TTTGTCAAGCCCTAAT,8917,3022,Stromal,Fibroblast,Fibroblast,COPD,8CO,8CO,COPD,8CO,8917,3022

In [10]:
adata_136831.obs = adata_136831.obs[['nCount_RNA', 'nFeature_RNA','sample', 'state']].copy()
adata_136831.obs

                       nCount_RNA  nFeature_RNA sample    state
001C_AAACCTGCATCGGGTC        5477          2150   001C  Control
001C_AAACCTGTCAACACCA       20311          4726   001C  Control
001C_AAACCTGTCACAGTAC        1390           881   001C  Control
001C_AAACCTGTCTGTCTAT        3968          1943   001C  Control
001C_AAACGGGAGACTAAGT        3036          1716   001C  Control
...                           ...           ...    ...      ...
8CO_TTGTAGGCATCACGTA         7617          2796    8CO     COPD
8CO_TTGTAGGTCCAGATCA         3904          1811    8CO     COPD
8CO_TTTATGCGTAGGCTGA         5195          2098    8CO     COPD
8CO_TTTGGTTTCTGCAAGT        24743          4819    8CO     COPD
8CO_TTTGTCAAGCCCTAAT         8917          3022    8CO     COPD

[312928 rows x 4 columns]

In [11]:
# 공통되는 유전자들만 사용하기
adata_merged = sc.concat(
    [adata_122960, adata_135893, adata_136831],
    label="journal",  # sample 정보가 새 column으로 생김
    keys=['GSE122960','GSE135893','GSE136831'],
    join='inner',
    index_unique=None
)

In [13]:
adata_IPF = adata_merged[adata_merged.obs["state"].isin(["Control", "IPF"])].copy()

In [14]:
adata_IPF.write("/home/jaehyunchoi/bystander_collaboration/Figure_script_IPF/revision/Data/public_data/Lung_public_atlas_001.h5ad")